### ISSUE TITLE
Brutus needs access permissions for this repo

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase-linux-appimage-template#41]
### Describe the bug

The pre-commit update job is [failing](https://github.com/beeware/briefcase-linux-appimage-template/actions/runs/6605968136/job/17941697457) since brutus doesn't have access to the repo.

```
Run peter-evans/create-pull-request@v5.0.2
Prepare git configuration
Determining the base and head repositories
Pull request branch target repository set to beeware/briefcase-linux-appimage-template
Configuring credential for HTTPS authentication
Checking the base repository state
Pull request branch to create or update set to 'autoupdates/pre-commit/pre-commit-hooks'
Configuring the committer and author
Create or update the pull request branch
Pushing pull request branch to 'origin/autoupdates/pre-commit/pre-commit-hooks'
  /usr/bin/git push --force-with-lease origin autoupdates/pre-commit/pre-commit-hooks:refs/heads/autoupdates/pre-commit/pre-commit-hooks
  remote: Permission to beeware/briefcase-linux-appimage-template.git denied to brutusthebee.
  fatal: unable to access 'https://github.com/beeware/briefcase-linux-appimage-template/': The requested URL returned error: 403
  Error: The process '/usr/bin/git' failed with exit code 128
Restore git configuration
```

### Steps to reproduce

See [CI](https://github.com/beeware/briefcase-linux-appimage-template/actions/workflows/pre-commit-update.yml).

### Expected behavior

CI succeeds.

### Environment

- Operating System:
- Python version:
- Software versions:
  - Briefcase:
  - Toga:
  - ...

**Comment by rmartin16** [comment]
Actually, this appears to be a more widespread problem; brutus needs access to this repos too:

Android - https://github.com/beeware/briefcase-android-gradle-template/actions/runs/6449759761/job/17508477846
iOS - https://github.com/beeware/briefcase-iOS-Xcode-template/actions/runs/6449677155/job/17508261752
AppImage - https://github.com/beeware/briefcase-linux-appimage-template/actions/runs/6449747743/job/17508432527
Flatpak - https://github.com/beeware/briefcase-linux-flatpak-template/actions/runs/6631288291/job/18014493186
macOS app - https://github.com/beeware/briefcase-macOS-app-template/actions/runs/6449767856/job/17508580033
macOS Xcode - https://github.com/beeware/briefcase-macOS-Xcode-template/actions/runs/6631508357/job/18015164985
web - https://github.com/beeware/briefcase-web-static-template/actions/runs/6631532733/job/18015235822
Windows app - https://github.com/beeware/briefcase-windows-app-template/actions/runs/6449735277/job/17508382550
Windows VS - https://github.com/beeware/briefcase-windows-VisualStudio-template/actions/runs/6631562848/job/18015354847

**Comment by freakboy3742** [comment]
I've added the `robots` group to all the repos listed above.

**Comment by rmartin16** [comment]
(just in case you didn't get a notification) beeware/briefcase-macOS-Xcode-template [errored](https://github.com/beeware/briefcase-macOS-Xcode-template/actions/runs/6763473017/job/18380644599#step:9:97) today with 403 :)

**Comment by freakboy3742** [comment]
Huh... I didn't.... but I'm watching all activity on the repo...

It's an easy fix - the robot permissions were mistakenly set to readonly. But I have no idea why I didn't get a notification...

**Comment by rmartin16** [comment]
I was a little surprised I was notified that an automated Action workflow failed....because I have never received a notification before. (at least for automated workflow runs....i definitely get all the emails for workflows that start via my PRs).

I can't remember if I recently changed this Actions Notification [setting](https://github.com/settings/notifications) recently...but maybe worth verifying....idk

**Comment by mhsmith** [comment]
I think you only get notified for action failures if you were the person who initiated them, but I don't know how that applies to robot accounts.
